// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalserosAttendance.Data;

namespace SalserosAttendance.Migrations
{
    [DbContext(typeof(SalserosAttendanceContext))]
    [Migration("20181026023657_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalserosAttendance.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("EventID");

                    b.Property<int>("MemberID");

                    b.HasKey("EventID", "MemberID");

                    b.HasIndex("MemberID");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("SalserosAttendance.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SalserosAttendance.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CollegeEmail");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("StudentNumber")
                        .HasMaxLength(7);

                    b.HasKey("MemberID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SalserosAttendance.Models.AttendanceRecord", b =>
                {
                    b.HasOne("SalserosAttendance.Models.Event", "Event")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SalserosAttendance.Models.Member", "Member")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
