// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalserosAttendance.Data;

namespace SalserosAttendance.Migrations
{
    [DbContext(typeof(SalserosAttendanceContext))]
    partial class SalserosAttendanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalserosAttendance.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceRecordID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.HasKey("AttendanceRecordID");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("SalserosAttendance.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AttendanceRecordID");

                    b.Property<string>("CollegeEmail");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("StudentNumber")
                        .HasMaxLength(7);

                    b.HasKey("MemberID");

                    b.HasIndex("AttendanceRecordID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SalserosAttendance.Models.Member", b =>
                {
                    b.HasOne("SalserosAttendance.Models.AttendanceRecord")
                        .WithMany("Members")
                        .HasForeignKey("AttendanceRecordID");
                });
#pragma warning restore 612, 618
        }
    }
}
